### ISSUE TITLE
About the training on FFHQ

### ISSUE THREAD

**Issue by AlbertHuyb** [Xuanmeng-Zhang/MVCGAN#4]
Hello @Xuanmeng-Zhang , thanks for yoru excellent work.

I want to confirm some details of training on FFHQ. 

1. Did you train with 8 GPU cards?
2. How long does it take to finish all the 3000 epochs?

Thanks

**Comment by Xuanmeng-Zhang** [comment]
Yes, 8 V100 for around ten days.

**Comment by AlbertHuyb** [comment]
Got it. Thank you.

**Comment by AlbertHuyb** [comment]
@Xuanmeng-Zhang , I'm also curious about the variables including  `h_mea=pi/2`, `h_stddev=0.3`, `v_mean=pi/2`, `v_stddev=0.155` and `fov=12 degree` in your metadata used when training on FFHQ dataset. 
How did you get these statistics from FFHQ? 

I'm not familiar with these variables. and I'd really appreciate it if you could help, 

Thanks

**Comment by 955999979** [comment]
> ，我也对在 FFHQ 数据集上训练时使用的元数据中的变量（包括 、 、 和）感到好奇。您是如何从FFHQ获得这些统计数据的？`h_mea=pi/2``h_stddev=0.3``v_mean=pi/2``v_stddev=0.155``fov=12 degree`
> 
> 我不熟悉这些变量。如果你能帮忙，我将不胜感激，
> 
> 谢谢

Do you understand these parameters? I'm also having the same problem as you, looking forward to your reply, thank you！

**Comment by 955999979** [comment]
> @Xuanmeng-Zhang , I'm also curious about the variables including `h_mea=pi/2`, `h_stddev=0.3`, `v_mean=pi/2`, `v_stddev=0.155` and `fov=12 degree` in your metadata used when training on FFHQ dataset. How did you get these statistics from FFHQ?
> 
> I'm not familiar with these variables. and I'd really appreciate it if you could help,
> 
> Thanks

Do you understand these parameters? I'm also having the same problem as you, looking forward to your reply, thank you！

**Comment by Xuanmeng-Zhang** [comment]
@AlbertHuyb @955999979 Hi, sorry for the late reply. We assume the face angle distribution is a Gaussian distribution, where the mean value is pi/2 (both in the vertical and horizontal directions). We set these parameters empirically. A more accurate way is to follow the eg3d to estimate the camera parameters from a pretrained face model. Please refer [eg3d](https://github.com/NVlabs/eg3d) to for more details.

**Comment by 955999979** [comment]
@Xuanmeng-Zhang  Okay, thank you for your reply.

**Comment by jasuriy** [comment]
Hi @Xuanmeng-Zhang  great job. I am fascinated . 
I am trying to do transfer learning on my custom dataset (which is similar to ffhq dataset) I am getting this error: 
CUDA_VISIBLE_DEVICES=0 python main.py --output_dir custom_exp --port 12361 --curriculum CustomDataset --load_dir pretrained_weights
Namespace(n_epochs=3000, sample_interval=200, output_dir='custom_exp', eval_dir='/data/xuanmeng/eval/', load_dir='pretrained_weights', curriculum='CustomDataset', eval_freq=2000, port='12361', set_step=None, model_save_interval=2000)
Traceback (most recent call last):
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/main.py", line 519, in <module>
    mp.spawn(train, args=(num_gpus, opt), nprocs=num_gpus, join=True)
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/main.py", line 116, in train
    discriminator = torch.load(os.path.join(opt.load_dir, 'discriminator.pth'), map_location=device)
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jasurbek/Documents/PAPER-materials/MVCGAN/mvcgan/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_weights/discriminator.pth'

where can I get these files? for generator.pth  ema.pth and ema2.pth I downloaded from https://drive.google.com/file/d/1bRB4-KxQplJryJvqyEa8Ixkf_BVm4Nn6/view
BUT can't find discriminator.pth

I would truly appreciate if you could help me. thank you.

**Comment by Xuanmeng-Zhang** [comment]
Hi @jasuriy , if you use a new dataset, it's suggested to train the discrimintator from scratch, because the discriminator is trained on FFHQ. You can comment this line.
